---
- hosts: localhost

  tasks:

  - name: Update and upgrade homebrew
    homebrew:
      update_homebrew: yes
      upgrade_all: yes

  - name: Install golang
    homebrew:
      name: go
      state: present

  - name: Install node
    homebrew:
      name: node
      state: present

  - name: Install maven
    homebrew:
      name: maven
      state: present
      
  - name: Install tmux
    homebrew: 
      name: tmux
      state: present

  - name: Install fzf
    homebrew:
      name: fzf
      state: present

  - name: Install tree
    homebrew:
      name: tree
      state: present

  - name: Install zsh-autosuggestions
    homebrew:
      name: zsh-autosuggestions
      state: present

  - name: Install zsh-syntax-highlighting
    homebrew:
      name: zsh-syntax-highlighting
      state: present

  - name: Install openjdk12
    homebrew_cask:
      name: adoptopenjdk12
      state: present

  - name: Install The Silver searcher(ag)
    homebrew:
      name: the_silver_searcher
      state: present

  - name: Install htop
    homebrew:
      name: htop
      state: present