---
- hosts: localhost

  tasks:

  - name: Update and upgrade homebrew
    homebrew:
      update_homebrew: yes
      upgrade_all: yes

  - name: Install golang
    homebrew:
      name: go
      state: present

  - name: Install node
    homebrew:
      name: node
      state: present

  - name: Install maven
    homebrew:
      name: maven
      state: present
      
  - name: Install tmux
    homebrew: 
      name: tmux
      state: present